#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/LogFunctions        # Tutorial log-file functions
#------------------------------------------------------------------------------

rm -rf constant/polyMesh
rm -rf 0
rm -rf processor*
rm -f log.*

#------------------------------------------------------------------------------
